name: "Test"
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "src/**/*"
      - "Cargo.*"
      - "build.sh"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "src/**/*"
      - "Cargo.*"
      - "build.sh"

  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: "Test benchmarks compile"
    runs-on: ubuntu-latest-m

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          version: 2025.1.6 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache

      - name: Test EQL for Postgres ${{ matrix.postgres-version }}
        run: |
          ./build.sh test
          # mise run --output prefix test
